### ISSUE TITLE
MIME type not exported

### ISSUE THREAD

**Issue by Unrud** [flathub/org.fontforge.FontForge#4]
The MIME type specification ``/app/share/mime/packages/fontforge.xml`` is not exported.
The file  must be renamed to ``org.fontforge.FontForge.xml``.

**Comment by TingPing** [comment]
Also any icons referenced in it must be renamed.

**Comment by muelli** [comment]
hrm. Do `rename-file` like stanzas exist?

**Comment by TingPing** [comment]
No.

**Comment by muelli** [comment]
I think I have exported the mime file with https://github.com/flathub/org.fontforge.FontForge/commit/ccb7f3455ee004fe71caca21ee3ac35ad3c8f8db
yet, the app is not showing up correctly: https://flathub.org/apps/details/org.fontforge.FontForge
There was a build failure: https://flathub.org/builds/#/builders/5/builds/399 but it seems to be a problem with the infrastructure rather than a problem with the appdata file, esp. because a new build went fine: https://flathub.org/builds/#/builders/32/builds/4817



what else is wrong with the app to now show up properly on flathub?

**Comment by Unrud** [comment]
> yet, the app is not showing up correctly:

I don't think a missing MIME type causes this problem.

> what else is wrong with the app to now show up properly on flathub?

The program install three (redundant?) files for AppStream:

  * ``/app/share/appdata/org.fontforge.FontForge.appdata.xml``
  * ``/app/share/metainfo/org.fontforge.FontForge.appdata.xml``
  * ``/app/share/metainfo/org.fontforge.FontForge.metainfo.xml``

The files are almost identical. The first two are missing ``name`` and ``summary``. The third file is complete.

Flatpak seems to get the metadata from ``/app/share/metainfo/org.fontforge.FontForge.metainfo.xml``, but Flathub checks ``/app/share/appdata/org.fontforge.FontForge.appdata.xml``.

Maybe this is causing the problem? I would try something like:
```
mv /app/share/metainfo/org.fontforge.FontForge.metainfo.xml /app/share/appdata/org.fontforge.FontForge.appdata.xml
rm -r /app/share/metainfo
```

**Comment by muelli** [comment]
I think the MIME file is exported. Let's follow up here reg. showing up on flathub: https://github.com/flathub/org.fontforge.FontForge/issues/3
